### ISSUE TITLE
Working test

### ISSUE THREAD

**Issue by hubertokf** [gmassei/pymcda#1]
Hey!

I'm wondering if you have a working test. I just want to understand how everything works here.

Thanks.

**Comment by gmassei** [comment]
you can find some example data in "pymcda/pymcda/data.csv" (or "data.txt", as you prefer).
Ask me if you need more info.
gm

**Comment by hubertokf** [comment]
Ok thanks! And about pymcda/_doc/test.py? Do you have a fresh copy of that? I think that that code is in a old version. I guess that after your last commit (efdc4bd) you have changed some nomenclature.

**Comment by gmassei** [comment]
Yes,
I'm working on it. I hope to complete a new test in a few days

**Comment by hubertokf** [comment]
ok! Thank you very much!

**Comment by gmassei** [comment]
I've upgrade test file (in _doc directory) with a simple example with  weighted sum. I hope it is useful, even if I'm still working on code.

**Comment by hubertokf** [comment]
Sure! I'll take a look. Thanks!
